import { Injectable } from '@angular/core';
import { saveAs } from 'file-saver'

@Injectable({
  providedIn: 'root'
})
export class UtilitiesService {

  constructor() { }



  printReport(username: String) {
    let printContents = [document.getElementById('printable').innerHTML];

    const months = ["JAN", "FEB", "MAR", "APR", "MAY", "JUN", "JUL", "AUG", "SEP", "OCT", "NOV", "DEC"];
    let current_datetime = new Date()
    let formatted_date = current_datetime.getDate() + "-" + months[current_datetime.getMonth()] + "-" + current_datetime.getFullYear()

    var popupWin = window.open('', '_blank', 'width=600,height=700');
    popupWin.document.open();
    // popupWin.document.write('<html>' +
    //   '<head>' +
    //   'Status:' + ' ' + "this.status" +
    //   '<br>' +
    //   '<br>' +
    //   'Date:' + ' ' + "this..date" + '<br>' + '<br>' +
    //   'Generated by:' + ' ' +
    //   this.username +
    //   '<br>' +
    //   '<br>' + '<br>' + '<br>' + '<br>' +
    //   '<style>' +
    //   '.noPrint' +
    //   '{\n' +
    //   '    display: none; !important;\n' +
    //   '  }</style></head><body onload="window.print()">' + printContents +
    //   '</body>' +
    //   '</html>');


    popupWin.document.write('<html>' +
      '<head>' +

      '<br>' +

      '<style>' +
      '.noPrint' +
      '{\n' +
      '    display: none; !important;\n' +
      '  }</style></head><body onload="window.print()">' + '<h3>' + username + '</h3>' + '<h4>' + formatted_date + '</h4>' + '<br>' + printContents + '</footer>',
      '</body>' +
      '</html>');
    popupWin.document.close();

  }
  exportToExcel(username: String) {
    let printContents: HTMLElement = document.getElementById('printable') as HTMLElement;

    var blob = new Blob([document.getElementById('printable').innerHTML], {
      type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet;charset=utf-8"
    });
    saveAs(blob, "Report.xls");

  }


}
